# Generated by Django 5.2.7 on 2025-11-18 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_createticket'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='createticket',
            old_name='problem_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='createticket',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='createticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High (Service Degradation)'), ('critical', 'Critical (Service Down)')], default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='createticket',
            name='title',
            field=models.CharField(default='no description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createticket',
            name='status',
            field=models.CharField(default='open', max_length=50),
        ),
        migrations.AlterField(
            model_name='createticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='createticket',
            table=None,
        ),
    ]
