# Generated by Django 5.2.7 on 2025-11-22 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_problem_description_createticket_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fa-laptop')", max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Technician Specialty',
                'verbose_name_plural': 'Technician Specialties',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.createticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Professional bio or description', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('average_rating', models.FloatField(default=4.0)),
                ('review_count', models.IntegerField(default=0)),
                ('experience_years', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=2.0, help_text='Average response time in hours')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('certification', models.CharField(blank=True, max_length=200, null=True)),
                ('languages', models.CharField(blank=True, help_text='Comma-separated list of languages', max_length=200, null=True)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='17:00')),
                ('accepts_emergency_calls', models.BooleanField(default=False)),
                ('completed_tickets', models.IntegerField(default=0)),
                ('success_rate', models.FloatField(default=95.0, help_text='Success rate percentage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='technician_profile', to='accounts.userprofile')),
                ('specialties', models.ManyToManyField(blank=True, related_name='technicians', to='accounts.technicianspecialty')),
            ],
            options={
                'verbose_name': 'Technician',
                'verbose_name_plural': 'Technicians',
            },
        ),
        migrations.CreateModel(
            name='AssistanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to=settings.AUTH_USER_MODEL)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='accounts.technician')),
            ],
            options={
                'verbose_name': 'Assistance Request',
                'verbose_name_plural': 'Assistance Requests',
            },
        ),
        migrations.CreateModel(
            name='TechnicianReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.technician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Review',
                'verbose_name_plural': 'Technician Reviews',
                'unique_together': {('technician', 'user')},
            },
        ),
    ]
