# Generated by Django 5.2.7 on 2025-11-23 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_technician_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistancerequest',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistance_requests', to='accounts.createticket'),
        ),
    ]
