# Generated by Django 5.2.7 on 2025-12-01 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_messageedithistory_remove_botchat_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='technicianreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='technicianreview',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.createticket'),
        ),
        migrations.AlterUniqueTogether(
            name='technicianreview',
            unique_together={('technician', 'user', 'ticket')},
        ),
    ]
