# Generated by Django 5.2.7 on 2025-11-29 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_messageedithistory_remove_botchat_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistancerequest',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistance_requests', to='accounts.technician'),
        ),
    ]
