# Generated by Django 5.2.7 on 2025-11-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_email_recovery_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='promotions',
            field=models.BooleanField(default=False),
        ),
    ]
