# Generated by Django 5.2.7 on 2025-12-02 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_technicianreview_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('icon', models.CharField(default='fa-question-circle', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'FAQ Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='bot_response_data',
            field=models.JSONField(blank=True, help_text='Structured data for bot responses (buttons, related FAQs, etc.)', null=True),
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('short_question', models.CharField(help_text='Short version for bot buttons', max_length=100)),
                ('answer', models.TextField()),
                ('short_answer', models.TextField(help_text='Brief answer for quick responses')),
                ('read_time', models.CharField(default='5 min read', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for bot matching')),
                ('bot_priority', models.IntegerField(default=0, help_text='Priority in bot responses (higher = more likely)')),
                ('show_in_dashboard', models.BooleanField(default=True, help_text='Show in dashboard troubleshooting')),
                ('show_in_bot_buttons', models.BooleanField(default=True, help_text='Show as quick buttons in bot chat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='accounts.faqcategory')),
            ],
            options={
                'ordering': ['order', 'question'],
            },
        ),
    ]
